# Exploratory Data Analysis
### Blair Lee - 005721089

The dataset that we will be using is the dataset on Lighting, Exposure, and Attractiveness. The data looks at examining if the lighting conditions of a picture changes the perceived attractiveness of a person in that picture. In a separate study, they researchers looked at if changing the exposure changes the attractiveness of a person. Before even starting, I did some research on pictures and the impacts of lighting and exposure. There are many ways to manipulate light in order to convey certain emotions, and it is very much related to exposure which is how much light reaches the camera sensor.

In [7]:
import pandas as pd
import numpy as np

lighting = pd.read_excel("20201228 Perception of Attractiveness Raw Data.xlsx", sheet_name = 0)
lighting.head()

,ResponseId,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,LocationLatitude,...,N3,N4,N5,N6,O1,O2,O3,O4,O5,O6
0,R_2QVUTvHQF2MIFRc,2020-08-10 20:57:02,2020-08-10 21:02:27,IP Address,100.14.1.231,100,324,True,2020-08-10 21:02:27.756,40.036407,...,8,8,8,7,7,7,7,7,7,7
1,R_sNA0Y7Wikfbjmoh,2020-08-10 14:26:38,2020-08-10 14:29:55,IP Address,100.7.25.54,100,196,True,2020-08-10 14:29:55.330,37.510895,...,6,6,7,7,4,6,7,7,7,5
2,R_3mjH4mWb8yz5oci,2020-08-10 20:06:48,2020-08-10 20:14:34,IP Address,103.104.49.153,100,465,True,2020-08-10 20:14:34.982,8.179001,...,7,6,7,6,5,6,4,4,4,4
3,R_1lsGctLd8WM6U9W,2020-08-10 18:18:03,2020-08-10 18:24:40,IP Address,103.110.237.214,100,397,True,2020-08-10 18:24:41.027,11.342804,...,9,10,10,9,5,7,5,6,6,6
4,R_3HztxfUfojAXTNT,2020-08-11 02:16:52,2020-08-11 02:21:06,IP Address,103.114.211.46,100,253,True,2020-08-11 02:21:06.996,11.007507,...,10,7,10,10,7,7,7,7,7,7

Looking at the scores, it is important to note that the columns are labeled by a letter and a number. The letter represents a participant/picture and the number represents the lighting condition. The data already seems very clean and usable for any analysis we would like to perform.

In [8]:
exposure = pd.read_excel("20201228 Perception of Attractiveness Raw Data.xlsx", sheet_name = 1)
exposure.head()

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,LocationLatitude,...,91,92,93,94,95,101,102,103,104,105
0,2020-11-07 12:04:28,2020-11-07 12:07:53,0,79.110.53.34,100,204,1,2020-11-07 12:07:53.825,R_3KZmLhM9GxlzOFm,36.168503,...,4,3,6,7,8,8,8,8,9,7
1,2020-11-07 12:04:40,2020-11-07 12:08:31,0,75.190.204.157,100,230,1,2020-11-07 12:08:31.316,R_BJTbzmzL62fahbz,35.401001,...,3,3,3,3,3,5,5,5,5,5
2,2020-11-07 12:04:13,2020-11-07 12:08:40,0,24.167.162.47,100,266,1,2020-11-07 12:08:40.842,R_UxLAf8XxkoX6qBj,36.032196,...,4,4,4,4,4,5,5,5,5,5
3,2020-11-07 12:05:01,2020-11-07 12:08:44,0,122.164.33.143,100,223,1,2020-11-07 12:08:44.983,R_2CwaqzLJonWy4zi,13.087799,...,1,2,4,4,4,4,7,6,6,6
4,2020-11-07 12:04:54,2020-11-07 12:08:55,0,103.66.79.87,100,241,1,2020-11-07 12:08:56.222,R_23fpZnxZtbx1clK,11.042007,...,3,3,4,4,3,6,10,9,7,7

Once again looking at the scores, the columns are labeled by "two" numbers. The first number ranges from 1 to 10 and corresponds to a lettered participant in the lighting conditions. The second number represents the exposure level. Just like the lighting data, the exposure data is very clean and easy to work with.

The first thing that I would be most curious about is the central scores for each lighting level and the center score for each exposure level. I can look to find these results by finding the mean and/or median for each column.

In [25]:
lighting_1 = pd.concat([lighting["A1"], lighting["B1"], lighting["D1"], lighting["G1"], lighting["H1"], lighting["I1"], lighting["J1"], lighting["K1"], lighting["N1"], lighting["O1"]])
lighting_2 = pd.concat([lighting["A2"], lighting["B2"], lighting["D2"], lighting["G2"], lighting["H2"], lighting["I2"], lighting["J2"], lighting["K2"], lighting["N2"], lighting["O2"]])
lighting_3 = pd.concat([lighting["A3"], lighting["B3"], lighting["D3"], lighting["G3"], lighting["H3"], lighting["I3"], lighting["J3"], lighting["K3"], lighting["N3"], lighting["O3"]])
lighting_4 = pd.concat([lighting["A4"], lighting["B4"], lighting["D4"], lighting["G4"], lighting["H4"], lighting["I4"], lighting["J4"], lighting["K4"], lighting["N4"], lighting["O4"]])
lighting_5 = pd.concat([lighting["A5"], lighting["B5"], lighting["D5"], lighting["G5"], lighting["H5"], lighting["I5"], lighting["J5"], lighting["K5"], lighting["N5"], lighting["O5"]])
lighting_6 = pd.concat([lighting["A6"], lighting["B6"], lighting["D6"], lighting["G6"], lighting["H6"], lighting["I6"], lighting["J6"], lighting["K6"], lighting["N6"], lighting["O6"]])

In [28]:
print(f"For lighting 1, the mean is {lighting_1.mean()} and the median is {lighting_1.median()}")
print(f"For lighting 2, the mean is {lighting_2.mean()} and the median is {lighting_2.median()}")
print(f"For lighting 3, the mean is {lighting_3.mean()} and the median is {lighting_3.median()}")
print(f"For lighting 4, the mean is {lighting_4.mean()} and the median is {lighting_4.median()}")
print(f"For lighting 5, the mean is {lighting_5.mean()} and the median is {lighting_5.median()}")
print(f"For lighting 6, the mean is {lighting_6.mean()} and the median is {lighting_6.median()}")

For lighting 1, the mean is 5.167 and the median is 5.0
For lighting 2, the mean is 5.3815 and the median is 6.0
For lighting 3, the mean is 5.4775 and the median is 6.0
For lighting 4, the mean is 5.375 and the median is 6.0
For lighting 5, the mean is 5.3715 and the median is 6.0
For lighting 6, the mean is 5.3185 and the median is 6.0

Without doing any statistical analysis, it appears that the scores are quite similar and perhaps the lighting does not significantly impact the attractiveness of someone. Of course, this needs to be verified perhaps with a hypothesis test later on. Lighting 3 which was a box light seems to just slightly edge out all the other lighting conditions, but it is likely some outliers impacted this outcome as the median is the same as for every lighting condition except 1.

Next, I wanted to find the measures of center for the exposure data and see the impacts on attractiveness.

In [34]:
exposure_1 = pd.concat([exposure[11], exposure[21], exposure[31], exposure[41], exposure[51], exposure[61], exposure[71], exposure[81], exposure[91], exposure[101]])
exposure_2 = pd.concat([exposure[12], exposure[22], exposure[32], exposure[42], exposure[52], exposure[62], exposure[72], exposure[82], exposure[92], exposure[102]])
exposure_3 = pd.concat([exposure[13], exposure[23], exposure[33], exposure[43], exposure[53], exposure[63], exposure[73], exposure[83], exposure[93], exposure[103]])
exposure_4 = pd.concat([exposure[14], exposure[24], exposure[34], exposure[44], exposure[54], exposure[64], exposure[74], exposure[84], exposure[94], exposure[104]])
exposure_5 = pd.concat([exposure[15], exposure[25], exposure[35], exposure[45], exposure[55], exposure[65], exposure[75], exposure[85], exposure[95], exposure[105]])

In [35]:
print(f"For exposure 1, the mean is {exposure_1.mean()} and the median is {exposure_1.median()}")
print(f"For exposure 2, the mean is {exposure_2.mean()} and the median is {exposure_2.median()}")
print(f"For exposure 3, the mean is {exposure_3.mean()} and the median is {exposure_3.median()}")
print(f"For exposure 4, the mean is {exposure_4.mean()} and the median is {exposure_4.median()}")
print(f"For exposure 5, the mean is {exposure_5.mean()} and the median is {exposure_5.median()}")

For exposure 1, the mean is 5.5415 and the median is 6.0
For exposure 2, the mean is 5.582 and the median is 6.0
For exposure 3, the mean is 5.576 and the median is 6.0
For exposure 4, the mean is 5.563 and the median is 6.0
For exposure 5, the mean is 5.504 and the median is 6.0

Looking at these results, it seems that exposure has an even less impact on the attractiveness of someone. All of the means are very close and the medians are all identical.

In looking for relationships, I was curious in looking at the differences between males and females and the scores that they give. Perhaps a big assumption, but I assume that females judge more harshly when compared to males and thus it would be interesting to see if they usually give a lower score to all of the pictures. It would also be interesting to look at age, race, and perhaps in a more complicated problem the geographical location of the judge.

In [60]:
start = 16
end = 76
compare = lighting.iloc[:, start:end]
compare["mean"] = compare.iloc[:, 1:60].mean(axis = 1)
compare.groupby(by = "Sex").agg(func = "mean")

,A1,A2,A3,A4,A5,A6,B1,B2,B3,B4,...,N3,N4,N5,N6,O1,O2,O3,O4,O5,mean
Sex,,,,,,,,,,,,,,,,,,,,,
Female,4.707692,5.200000,5.015385,5.046154,5.307692,5.215385,3.384615,3.646154,3.815385,3.584615,...,6.230769,6.446154,6.538462,5.938462,4.538462,4.753846,4.615385,4.415385,4.707692,5.222425
Male,5.325926,5.377778,5.555556,5.311111,5.429630,5.585185,3.525926,3.622222,3.888889,3.629630,...,6.992593,6.896296,6.948148,6.659259,4.940741,4.948148,4.940741,4.733333,4.859259,5.424105

It seems that generally, both genders will give similar scores. However, for a few lighting conditions and a few participants, there seems to be a bit of a gap between the average scores. It would be interesting to compute some hypothesis tests.

In looking to complete some potential hypotheses to test, I would look to see if there are significant differences between the different lighting and exposure groups. This can be completed using an ANOVA test. This can be used to find between-group variance and perhaps within-group variances for specific participants.