## Team Activity 05.1

Names:

In [52]:
import numpy as np
import pandas as pd
from datetime import datetime

traffic = pd.read_csv("tc.csv")
traffic.head()

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,200704291,01/07/2020,01/01/2019,1033,7,Wilshire,793,997,TRAFFIC COLLISION,3004 3028 3030 3037 3101 3401 3701 4027 3035,...,STREET,CRENSHAW,WASHINGTON,"(34.0399, -118.3311)",23080.0,651.0,1105.0,NaN,12.0,69.0
1,192004028,01/01/2019,01/01/2019,820,20,Olympic,2088,997,TRAFFIC COLLISION,3004 3028 3030 3035 3036 3101 3401 3701 4020,...,STREET,MENLO AV,PICO BL,"(34.0421, -118.2879)",22723.0,671.0,950.0,NaN,11.0,8.0
2,191418727,08/25/2019,01/01/2019,2250,14,Pacific,1494,997,TRAFFIC COLLISION,3003 3025 3029 3035 3037 3101 3401 3701 4027,...,STREET,VICKSBURG,CENTURY,"(33.942, -118.4095)",23676.0,2340.0,445.0,12.0,10.0,16.0
3,190104049,01/01/2019,01/01/2019,1630,1,Central,111,997,TRAFFIC COLLISION,3101 3401 3701 3004 3025 3029,...,STREET,SUNSET BL,FIGUEROA ST,"(34.0627, -118.2463)",22728.0,538.0,449.0,NaN,11.0,28.0
4,190104026,01/01/2019,01/01/2019,330,1,Central,129,997,TRAFFIC COLLISION,3101 3401 3701 3004 3026 3036,...,STREET,N ALAMEDA,E CESAR CHAVEZ,"(34.0511, -118.2336)",22728.0,533.0,466.0,NaN,9.0,28.0

In [54]:
traffic["Date Occurred"] = pd.to_datetime(traffic["Date Occurred"])
traffic["Date Reported"] = pd.to_datetime(traffic["Date Reported"])
traffic["Time Occurred"] = pd.to_datetime(traffic["Time Occurred"], format = '%H%M', errors = "coerce").dt.time
traffic.head(100)

,DR Number,Date Reported,Date Occurred,Time Occurred,Area ID,Area Name,Reporting District,Crime Code,Crime Code Description,MO Codes,...,Premise Description,Address,Cross Street,Location,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,200704291,2020-01-07,2019-01-01,10:33:00,7,Wilshire,793,997,TRAFFIC COLLISION,3004 3028 3030 3037 3101 3401 3701 4027 3035,...,STREET,CRENSHAW,WASHINGTON,"(34.0399, -118.3311)",23080.0,651.0,1105.0,NaN,12.0,69.0
1,192004028,2019-01-01,2019-01-01,08:20:00,20,Olympic,2088,997,TRAFFIC COLLISION,3004 3028 3030 3035 3036 3101 3401 3701 4020,...,STREET,MENLO AV,PICO BL,"(34.0421, -118.2879)",22723.0,671.0,950.0,NaN,11.0,8.0
2,191418727,2019-08-25,2019-01-01,22:50:00,14,Pacific,1494,997,TRAFFIC COLLISION,3003 3025 3029 3035 3037 3101 3401 3701 4027,...,STREET,VICKSBURG,CENTURY,"(33.942, -118.4095)",23676.0,2340.0,445.0,12.0,10.0,16.0
3,190104049,2019-01-01,2019-01-01,16:30:00,1,Central,111,997,TRAFFIC COLLISION,3101 3401 3701 3004 3025 3029,...,STREET,SUNSET BL,FIGUEROA ST,"(34.0627, -118.2463)",22728.0,538.0,449.0,NaN,11.0,28.0
4,190104026,2019-01-01,2019-01-01,03:30:00,1,Central,129,997,TRAFFIC COLLISION,3101 3401 3701 3004 3026 3036,...,STREET,N ALAMEDA,E CESAR CHAVEZ,"(34.0511, -118.2336)",22728.0,533.0,466.0,NaN,9.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,191904029,2019-01-01,2019-01-01,20:00:00,19,Mission,1907,997,TRAFFIC COLLISION,3004 3028 3030 3037 3101 3401 3701 4026,...,STREET,FENTON AV,MACLAY ST,"(34.3033, -118.414)",18912.0,41.0,890.0,NaN,1.0,47.0
96,191804071,2019-01-01,2019-01-01,08:50:00,18,Southeast,1806,997,TRAFFIC COLLISION,3006 3028 3030 3101 4018,...,STREET,CENTRAL AV,91ST ST,"(33.9539, -118.2564)",22351.0,799.0,1174.0,7.0,13.0,45.0
97,191904285,2019-01-07,2019-01-01,06:00:00,19,Mission,1982,997,TRAFFIC COLLISION,3006 3030 3028 3037 3101 3401 3701 4019,...,STREET,BURNET AV,PARTHENIA ST,"(34.2283, -118.4633)",18914.0,126.0,420.0,NaN,3.0,73.0
98,191804082,2019-01-01,2019-01-01,09:00:00,18,Southeast,1863,997,TRAFFIC COLLISION,4025 3037 3006 3030 3101,...,STREET,300 E 115TH ST,NaN,"(33.9301, -118.2695)",24355.0,809.0,1194.0,7.0,15.0,53.0
99,191904224,2019-01-01,2019-01-01,21:00:00,19,Mission,1987,997,TRAFFIC COLLISION,3006 3025 3037 3101 3401 3701 4019 3039,...,STREET,CANTALOUPE AV,CHASE ST,"(34.2268, -118.4366)",19730.0,151.0,307.0,NaN,3.0,59.0

In [26]:
DR_number = traffic["DR Number"]
dr_number = traffic.iloc[:, 0]

print(DR_number)
print(dr_number)

# It is likely much more helpful to use column names 
# since large dataframes will likely have many indices.

0         200704291
1         192004028
2         191418727
3         190104049
4         190104026
            ...
134168    230204688
134169    230904001
134170    222019939
134171    230106871
134172    231808015
Name: DR Number, Length: 134173, dtype: int64
0         200704291
1         192004028
2         191418727
3         190104049
4         190104026
            ...
134168    230204688
134169    230904001
134170    222019939
134171    230106871
134172    231808015
Name: DR Number, Length: 134173, dtype: int64

In [37]:
print(traffic["Victim Age"].describe())
print(traffic["Time Occurred"].describe())

count    123750.000000
mean         40.279394
std          17.365037
min          10.000000
25%          27.000000
50%          37.000000
75%          51.000000
max          99.000000
Name: Victim Age, dtype: float64
count    134173.000000
mean       1356.676559
std         613.193184
min           1.000000
25%         930.000000
50%        1430.000000
75%        1830.000000
max        2359.000000
Name: Time Occurred, dtype: float64

In [ ]:
print(traffic["Area Name"].describe())